volumes:
  platform_django_local_postgres_data: {}
  platform_django_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: platform_django_${WORKTREE_ID:-main}_django
    container_name: platform_django_${WORKTREE_ID:-main}_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    environment:
      - VITE_PLATFORM_DJANGO_PORT=${VITE_PLATFORM_DJANGO_PORT:-5173}
    ports:
      - '${DOCKER_HOST_DJANGO_PORT:-8000}:8000'
    command: /start

  postgres:
    image: docker.io/postgres:18
    container_name: platform_django_${WORKTREE_ID:-main}_postgres
    volumes:
      - platform_django_local_postgres_data:/var/lib/postgresql
    ports:
      - '${DOCKER_HOST_POSTGRES_PORT:-5432}:5432'
    env_file:
      - ./.env

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: platform_django_${WORKTREE_ID:-main}_mailpit
    profiles: [mail]
    ports:
      - '${DOCKER_HOST_MAILPIT_PORT:-8025}:8025'

  redis:
    image: docker.io/redis:8.6
    container_name: platform_django_${WORKTREE_ID:-main}_redis
    volumes:
      - platform_django_local_redis_data:/data
    ports:
      - '${DOCKER_HOST_REDIS_PORT:-6379}:6379'

  celeryworker:
    <<: *django
    container_name: platform_django_${WORKTREE_ID:-main}_celeryworker
    profiles: [celery]
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: platform_django_${WORKTREE_ID:-main}_celerybeat
    profiles: [celery]
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    container_name: platform_django_${WORKTREE_ID:-main}_flower
    profiles: [flower]
    ports:
      - '${DOCKER_HOST_FLOWER_PORT:-5555}:5555'
    command: /start-flower
