// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { type Options, schemaRetrieve, usersList, usersMeRetrieve, usersPartialUpdate, usersRetrieve, usersUpdate } from '../sdk.gen';
import type { SchemaRetrieveData, SchemaRetrieveResponse, UsersListData, UsersListResponse, UsersMeRetrieveData, UsersMeRetrieveResponse, UsersPartialUpdateData, UsersPartialUpdateResponse, UsersRetrieveData, UsersRetrieveResponse, UsersUpdateData, UsersUpdateResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const schemaRetrieveQueryKey = (options?: Options<SchemaRetrieveData>) => createQueryKey('schemaRetrieve', options);

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieveOptions = (options?: Options<SchemaRetrieveData>) => queryOptions<SchemaRetrieveResponse, DefaultError, SchemaRetrieveResponse, ReturnType<typeof schemaRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await schemaRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: schemaRetrieveQueryKey(options)
});

export const usersListQueryKey = (options?: Options<UsersListData>) => createQueryKey('usersList', options);

export const usersListOptions = (options?: Options<UsersListData>) => queryOptions<UsersListResponse, DefaultError, UsersListResponse, ReturnType<typeof usersListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersListQueryKey(options)
});

export const usersRetrieveQueryKey = (options: Options<UsersRetrieveData>) => createQueryKey('usersRetrieve', options);

export const usersRetrieveOptions = (options: Options<UsersRetrieveData>) => queryOptions<UsersRetrieveResponse, DefaultError, UsersRetrieveResponse, ReturnType<typeof usersRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersRetrieveQueryKey(options)
});

export const usersPartialUpdateMutation = (options?: Partial<Options<UsersPartialUpdateData>>): UseMutationOptions<UsersPartialUpdateResponse, DefaultError, Options<UsersPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<UsersPartialUpdateResponse, DefaultError, Options<UsersPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersUpdateMutation = (options?: Partial<Options<UsersUpdateData>>): UseMutationOptions<UsersUpdateResponse, DefaultError, Options<UsersUpdateData>> => {
    const mutationOptions: UseMutationOptions<UsersUpdateResponse, DefaultError, Options<UsersUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersMeRetrieveQueryKey = (options?: Options<UsersMeRetrieveData>) => createQueryKey('usersMeRetrieve', options);

export const usersMeRetrieveOptions = (options?: Options<UsersMeRetrieveData>) => queryOptions<UsersMeRetrieveResponse, DefaultError, UsersMeRetrieveResponse, ReturnType<typeof usersMeRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersMeRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersMeRetrieveQueryKey(options)
});
