// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { SchemaRetrieveData, SchemaRetrieveResponses, UsersListData, UsersListResponses, UsersMeRetrieveData, UsersMeRetrieveResponses, UsersPartialUpdateData, UsersPartialUpdateResponses, UsersRetrieveData, UsersRetrieveResponses, UsersUpdateData, UsersUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<SchemaRetrieveData, ThrowOnError>): RequestResult<SchemaRetrieveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SchemaRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/schema/',
    ...options
});

/**
 * Orchestration only: reads call the selector, writes call the service.
 */
export const usersList = <ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>): RequestResult<UsersListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersListResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/',
    ...options
});

/**
 * Orchestration only: reads call the selector, writes call the service.
 */
export const usersRetrieve = <ThrowOnError extends boolean = false>(options: Options<UsersRetrieveData, ThrowOnError>): RequestResult<UsersRetrieveResponses, unknown, ThrowOnError> => (options.client ?? client).get<UsersRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options
});

/**
 * Orchestration only: reads call the selector, writes call the service.
 */
export const usersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersPartialUpdateData, ThrowOnError>): RequestResult<UsersPartialUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UsersPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Orchestration only: reads call the selector, writes call the service.
 */
export const usersUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateData, ThrowOnError>): RequestResult<UsersUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<UsersUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Orchestration only: reads call the selector, writes call the service.
 */
export const usersMeRetrieve = <ThrowOnError extends boolean = false>(options?: Options<UsersMeRetrieveData, ThrowOnError>): RequestResult<UsersMeRetrieveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersMeRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/me/',
    ...options
});
