// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { SchemaRetrieveData, SchemaRetrieveResponses, UsersListData, UsersListResponses, UsersMeRetrieveData, UsersMeRetrieveResponses, UsersPartialUpdateData, UsersPartialUpdateResponses, UsersRetrieveData, UsersRetrieveResponses, UsersUpdateData, UsersUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<SchemaRetrieveData, ThrowOnError>) => (options?.client ?? client).get<SchemaRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/schema/',
    ...options
});

export const usersList = <ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>) => (options?.client ?? client).get<UsersListResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/',
    ...options
});

export const usersRetrieve = <ThrowOnError extends boolean = false>(options: Options<UsersRetrieveData, ThrowOnError>) => (options.client ?? client).get<UsersRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options
});

export const usersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<UsersPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const usersUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateData, ThrowOnError>) => (options.client ?? client).put<UsersUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/{username}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const usersMeRetrieve = <ThrowOnError extends boolean = false>(options?: Options<UsersMeRetrieveData, ThrowOnError>) => (options?.client ?? client).get<UsersMeRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/users/me/',
    ...options
});
